#! /usr/bin/env python

""" Build file for the interposing library. """

import os

__author__ = 'Alex Merritt'
__email__ = 'merritt.alex@gatech.edu'

Import('env')

sources = []

def find_sources(paths):
    global sources
    for dir in paths:
        files = os.listdir(dir)
        for src in files:
            (name,ext) = os.path.splitext(src)
            if '.c' == ext.lower():
                sources.append(dir + src)

find_sources(['./', 'api/', '../assembly/', '../cuda/', '../io/', '../'])
sources.remove('../runtime.c')
sources.remove('../assembly/remotesink.c')

lib = env.SharedLibrary('libsfcuda.so', sources)
#env.Install(INSTALL_DIR + '/lib', lib)
