"""@file SConstruct
   @author Magdalena Slawinska magg@gatech.edu
   @date 2011-02-22
   @brief Building the network stuff
"""

import os

Import('CUDA_ROOT', 'INIPARSER')

envBackend = Environment(
  LIBS=['pthread', 
        'rt', 
        'dl', 
        'cudart', 
        'iniparser', 
        'glib-2.0' ],
  LIBPATH=[CUDA_ROOT + 'lib64', INIPARSER ],
  CPPPATH=['.',
  '../remote',
  '../include',
  '../interposer',
  '../backend',
  CUDA_ROOT + 'include',
  INIPARSER + 'src',
  '/usr/include/glib-2.0',
  '/usr/lib64/glib-2.0/include'],
  CCFLAGS='-g -Wall -Wextra')
			 
envBackend.Program('backend', [
			'backend.c',
			'../interposer/libciutils.c',
			'../remote/connection.c',
			'../remote/remote_packet.c',
			'../remote/remote_api_wrapper.c',
            '../include/kidron_common_f.c'])
