"""@file SConstruct
   @author Magdalena Slawinska magg@gatech.edu
   @date 2011-02-22
   @brief Building the network stuff
"""

import os

Import('CUDA_ROOT', 
       'GLIB20')

envBackend = Environment(
  LIBS=['pthread', 
        'rt', 
        'dl', 
        'cudart', 
        'glib-2.0' ],
  LIBPATH=[CUDA_ROOT + 'lib64',
           GLIB20 + 'lib'],
  CPPPATH=['.',
  '../remote',
  '../include',
  '../interposer',
  '../backend',
  CUDA_ROOT + 'include',
  GLIB20 + 'include/glib-2.0',
  GLIB20 + 'include/gio-unix-2.0',
  GLIB20 + 'lib/glib-2.0/include'
  #'/usr/include/glib-2.0',
  #'/usr/lib64/glib-2.0/include'
  ],
  CCFLAGS='-g -Wall -Wextra')
			 
envBackend.Program('backend', [
			'backend.c',
			'../interposer/libciutils.c',
			'../remote/connection.c',
			'../remote/remote_packet.c',
			'../remote/remote_api_wrapper.c',
            '../include/kidron_common_f.c'])
