"""
	@file SConstruct
	@date Dec 20, 2011
	@author Magdalena Slawinska a.k.a. Magic Magg magg dot gatech @ gmail dot edu
"""

envTest = Environment(CPPPATH = ['../include'],
					CCFLAGS = ['-ggdb', '-O0'],
					LIBPATH = ['..'],
					LIBS = ['shmgrp'])

envTest.Program('test_leader.c')
envTest.Program('test_member.c')
envTest.Program('hacktest_leader.c')
envTest.Program('hacktest_child.c')