#! /usr/bin/env python

"""@file SConstruct
   @author Magdalena Slawinska magg@gatech.edu
   @author Alex Merritt, merritt.alex@gatech.edu
   @date 2011-02-15
   @brief Building the interposer
"""

Import('CUDA_ROOT', 
       'INSTALL_DIR',        
       'BASE_ENV')

env = BASE_ENV.Clone()

env.Append(LIBS = ['rt', 'dl', 'shmgrp'])
env.Append(LIBPATH = [CUDA_ROOT + '/lib64', '/lib64', '../shmgrp'])
env.Append(CPPPATH = [ '.', CUDA_ROOT + '/include', '../include', '../shmgrp/include']) 
env.Append(CCFLAGS = ['-Werror'])

LIBCI_LIB = 'libci.so'
env.SharedLibrary(LIBCI_LIB, [ 'libci.c', '../common/cuda/marshal.c'])

env.Install(INSTALL_DIR+'/lib', LIBCI_LIB)
