"""@file SConstruct
   @author Magdalena Slawinska magg@gatech.edu
   @date 2011-09-26
   @brief Building the vc_manager stuff. 
"""

import os

# we import CUDA_ROOT to have packetheader.h driver_types.h and vector_types.h
Import('GLIB20', 'CUDA_ROOT')

envVCManager = Environment(
  LIBS=['pthread', 
#        'rt', 
#        'dl', 
#        'cudart', 
        'glib-2.0',
        # from libci we want connection and kidron_common_f.c
        'libci' ], 
  LIBPATH=[
           #CUDA_ROOT + 'lib64',
           GLIB20 + 'lib',
           '../interposer'],
  CPPPATH=['.',
  '../remote',
  '../include',
  '../interposer',
  '../backend',
  CUDA_ROOT + 'include',  # packetheader.h requires it
  GLIB20 + 'include/glib-2.0',
  GLIB20 + 'include/gio-unix-2.0',
  GLIB20 + 'lib/glib-2.0/include'
  ],
  CCFLAGS='-g -Wall -Wextra')
			 
envVCManager.Program('vc_manager', [
			'vc_manager.c',
		#	'../interposer/libciutils.c',
		#	'../remote/connection.c',
		#	'../remote/remote_packet.c',
		#	'../remote/remote_api_wrapper.c',
        #    '../include/kidron_common_f.c']
                     ])
