#! /usr/bin/env python

""" Build file for the daemon. """

import os
import commands
import sys

__author__ = 'Alex Merritt'
__email__ = 'merritt.alex@gatech.edu'

Import('env')

env.Append(LIBS = ['pthread', 'uuid', 'cudart', 'cuda'])

sources = []

def find_sources(paths):
    global sources
    for dir in paths:
        files = os.listdir(dir)
        for src in files:
            (name,ext) = os.path.splitext(src)
            if '.c' == ext.lower():
                sources.append(dir + src)

find_sources(['./', 'cuda/', 'io/', 'assembly/'])

prog = env.Program('shadowfax', sources)
#env.Install(INSTALL_DIR + '/bin', prog)

SConscript(['lib/SConstruct'])
