#! /usr/bin/env python

""" Build file for the backend code. """

import os
import commands
import sys

__author__ = 'Alex Merritt'
__email__ = 'merritt.alex@gatech.edu'

Import('NODE_NAME', 'ENV', 'INSTALL_DIR')

env = ENV[NODE_NAME]
env.Append(LIBS = ['pthread', 'uuid', 'cudart', 'cuda'])

sources = []

files = os.listdir('./')
for src in files:
	(name,ext) = os.path.splitext(src)
	if name in ['runtime', 'localsink']:
		continue
	if '.c' == ext.lower():
		sources.append(src)

files = os.listdir('assembly/')
for src in files:
	(name,ext) = os.path.splitext(src)
	if '.c' == ext.lower():
		sources.append('assembly/' + src)

sources.append('../common/cuda/execute.c')
sources.append('../common/cuda/marshal_hidden.c')
sources.append('../common/cuda/rpc.c')
sources.append('../common/cuda/bypass.c')
sources.append('../common/io/sock.c')
sources.append('../common/util/rbtree.c')
sources.append('../common/mq.c')

biny = env.Program('shadowfax', ['runtime.c', sources])
env.Install(INSTALL_DIR + '/bin', biny)

#biny = env.Program('remotesink', ['assembly/remotesink.c', sources])
#env.Install(INSTALL_DIR + '/bin', biny)
